spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chatdb}
    username: ${SPRING_DATASOURCE_USERNAME:eskil}
    password: ${SPRING_DATASOURCE_PASSWORD:password1}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: 'true'
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
  web:
    error:
      include-message: always
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      username: ${SPRING_DATA_REDIS_USERNAME:}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: 10000

server:
  port: ${PORT:5050}

app:
  crypto:
    messageKeyV1B64: ${APP_MESSAGE_KEY_V1_B64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=}
  jwt:
    secret: ${JWT_SECRET:superSecretKeyForTheDevelopmentWhichIsAbsolutelySecureEnoughAndFarEnoughBitsToBeAbleToBeMadeIntoASecureEnoughKey}